// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATet4muCmfGF7O1LAnn_wstGPV0RT07J8',
    appId: '1:211097703077:web:76b6efd1b39929d9beb34c',
    messagingSenderId: '211097703077',
    projectId: 'offline-fa2c5',
    authDomain: 'offline-fa2c5.firebaseapp.com',
    storageBucket: 'offline-fa2c5.firebasestorage.app',
    measurementId: 'G-T8ZH9HFRXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_cCPCsJXCWZ4sjALRG08Awi3Qe_OgRI',
    appId: '1:211097703077:android:3ea761a4090367e0beb34c',
    messagingSenderId: '211097703077',
    projectId: 'offline-fa2c5',
    storageBucket: 'offline-fa2c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2jmjHd5AJdHymT088A3GLmEL-mlSVHw',
    appId: '1:211097703077:ios:5fcf0632483ea26bbeb34c',
    messagingSenderId: '211097703077',
    projectId: 'offline-fa2c5',
    storageBucket: 'offline-fa2c5.firebasestorage.app',
    iosBundleId: 'in.easycloud.offlineFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2jmjHd5AJdHymT088A3GLmEL-mlSVHw',
    appId: '1:211097703077:ios:5fcf0632483ea26bbeb34c',
    messagingSenderId: '211097703077',
    projectId: 'offline-fa2c5',
    storageBucket: 'offline-fa2c5.firebasestorage.app',
    iosBundleId: 'in.easycloud.offlineFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATet4muCmfGF7O1LAnn_wstGPV0RT07J8',
    appId: '1:211097703077:web:bb3d4a3ad4e4be81beb34c',
    messagingSenderId: '211097703077',
    projectId: 'offline-fa2c5',
    authDomain: 'offline-fa2c5.firebaseapp.com',
    storageBucket: 'offline-fa2c5.firebasestorage.app',
    measurementId: 'G-WV2Y5W4VTQ',
  );
}
